FROM gradle:jdk11-openj9 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon 

FROM openjdk:11-jdk
ARG JAR_FILE=target/*.jar
# RUN chmod +x gradlew
# RUN gradlew build
# CMD ["./gradlew", "build"]
COPY --from=build /home/gradle/src/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
# EXPOSE 8080
