spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 768435042402-lc8p0l5blqou7u5tjno1m2rf17eo6qv7.apps.googleusercontent.com
            clientSecret: WgtAjQynz-FidgqO4GX8ihKn
